### ISSUE TITLE
Add flags to configure secure connection client certificate

### ISSUE THREAD

**Issue by gkoitchev-bosch** [eclipse-kanto/software-update#10]
After filtering out the insecure connections with HTTPS scheme, we need to have option to configure loading client certificate from file. 
So, everywhere, where client certificate is mentioned, there are added parameters for the certificate and the key.
Currently, the system pool is used.

**Comment by e-grigorov** [comment]
What is the scope of this task i.e. is it only about the download operation or it'll cover some other connections? If the scope is only the download, I would like to suggest to clarify the description. Currently:
- download is not mentioned in the title/description
- "after filtering out the insecure connections with HTTPS scheme" - what is the task behind this?
- "everywhere, where client certificate is mentioned" - the task description doesn't need to have implementation details but we have to be more concrete about the use case. Just "everywhere" doesn't provide useful information.
