### ISSUE TITLE
Consider setting progress when operation status is changed to DOWNLOADING or INSTALLING/INSTALLED

### ISSUE THREAD

**Issue by gboyvalenkov-bosch** [eclipse-kanto/software-update#31]
Currently the event status sequence, when downloading an artifact is STARTED, DOWNLOADING(without a progress parameter set), DOWNLOADING(with progress set at 100%), DOWNLOADED. It seems more informative to set a progress to 0, when sending the first DOWNLOADING status event.
When installing an artifact, additional events are generated: INSTALLING, INSTALLED. Both of them do not include a progress parameter. It seems more informative to set the progress to 0 and 100, respectively.

**Comment by Mahesha-M** [comment]
I see this is good to have feature and I would like to take this activity.
